# -*- coding: utf-8 -*-
"""Electricity Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWsD1WyVZb5jzv3YAfbBgAmhwrVDymAC

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("datasetsmall.csv")

"""**Data Exploration**"""

df

print("Dataset Shape:", df.shape)

df.columns

df.info()

df.isnull().sum()

"""**Outlier Detection**"""

numeric_columns = df.select_dtypes(include=np.number).columns
# ID aur target ko outlier detection se exclude karna
numeric_columns = numeric_columns.drop(["CONS_NO", "FLAG"], errors="ignore")
n = len(numeric_columns)
cols = 5
rows = int(np.ceil(n / cols))
fig, axes = plt.subplots(rows, cols, figsize=(18, rows * 4))
axes = np.array(axes).flatten()
for ax, col in zip(axes, numeric_columns):
    sns.boxplot(x=df[col], ax=ax)
    ax.set_title(f"Box Plot - {col}")
    ax.set_xlabel(col)
    ax.grid(axis="x", alpha=0.3)
# Extra empty plots remove
for ax in axes[len(numeric_columns):]:
    ax.remove()
plt.suptitle("Outlier Detection Using Box Plots", fontsize=16)
plt.tight_layout()
plt.show()

# Fill missing values in numerical columns with median
numeric_columns = df.select_dtypes(include=np.number).columns
for col in numeric_columns:
    if col not in ["FLAG"]:
        df[col] = df[col].fillna(df[col].median())
print("Missing values after filling:")
print(df.isnull().sum())

"""**Count Plot(Target Distribution)**"""

plt.figure(figsize=(7, 5))
ax = sns.countplot(data=df, x="FLAG")
for container in ax.containers:
    ax.bar_label(container)
plt.title("Target Distribution")
plt.xlabel("FLAG")
plt.ylabel("Count")
plt.show()

"""**Data Preprocessing**"""

df.duplicated().sum()

"""**Feature Selection**"""

# Drop ID column
df = df.drop("CONS_NO", axis=1)
# Separate Features and Target
X = df.drop("FLAG", axis=1)
y = df["FLAG"]
print("Input Features Shape:", X.shape)
print("Target Shape:", y.shape)
X.head()

"""**Train-Test Split**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

"""**Class distribution check**"""

print("Training Data:")
print(y_train.value_counts())

print("\nTesting Data:")
print(y_test.value_counts())

"""# Working With Imblance Dataset

**CatBoost Classifier**
"""

!pip install catboost

from catboost import CatBoostClassifier
# Create CatBoost Classifier
cat_model = CatBoostClassifier(
    iterations=200,
    learning_rate=0.05,
    depth=6,
    random_seed=42,
    verbose=0
)
# Train the model
cat_model.fit(X_train, y_train)
print("CatBoost Classifier trained successfully!")

"""**Prediction**"""

# Predict classes
y_pred = cat_model.predict(X_test)
# Convert predictions to 1D array
y_pred = y_pred.astype(int).ravel()
print("Predicted Values:")
print(y_pred)

# Predicted Probabilities
y_pred_proba = cat_model.predict_proba(X_test)[:, 1]
print("Predicted Probabilities:")
print(y_pred_proba)

"""**Actual vs Predicted Table**"""

actual_predicted = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})
actual_predicted.head(20)

"""**Model Evaluation**"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
roc_auc = roc_auc_score(y_test, y_pred_proba)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC:", roc_auc)

"""**Evaluation Table**"""

evaluation = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"],
    "CatBoost": [accuracy, precision, recall, f1, roc_auc]
})
evaluation

"""**Confusion Matrix**"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Class 0", "Class 1"]
)
disp.plot()
plt.title("CatBoost Confusion Matrix")
plt.show()

"""**ROC-AUC Graph**"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
# Calculate ROC values
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
# Calculate AUC
roc_auc = roc_auc_score(y_test, y_pred_proba)
# Plot ROC Curve
plt.figure(figsize=(8, 6))
plt.plot(
    fpr,
    tpr,
    linewidth=2,
    label=f"CatBoost (AUC = {roc_auc:.3f})"
)
plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    linewidth=1.5,
    label="Random Classifier"
)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-AUC Curve")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""# Working With Imblance Dataset

**SMOTE — Balance Training Data**
"""

from imblearn.over_sampling import SMOTE
# Create SMOTE object
smote = SMOTE(random_state=42)
# Apply SMOTE only on training data
X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)
print("Before SMOTE:")
print(y_train.value_counts())
print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

"""**Class Distribution Graph**"""

plt.figure(figsize=(7, 5))
sns.countplot(x=y_train_smote)
plt.title("Class Distribution After SMOTE")
plt.xlabel("FLAG")
plt.ylabel("Count")
plt.show()

"""**CatBoost Classifier — After SMOTE**"""

from catboost import CatBoostClassifier
# Create CatBoost model
cat_model_smote = CatBoostClassifier(
    iterations=200,
    learning_rate=0.05,
    depth=6,
    random_seed=42,
    verbose=0
)
# Train on SMOTE-balanced data
cat_model_smote.fit(X_train_smote, y_train_smote)
print("CatBoost trained successfully on SMOTE-balanced data!")

"""**Prediction**"""

# Predict classes on the original test data
y_pred_smote = cat_model_smote.predict(X_test)
# Convert to 1D array
y_pred_smote = y_pred_smote.astype(int).ravel()
print("Predicted Values:")
print(y_pred_smote)

# Predicted Probabilities
y_pred_proba_smote = cat_model_smote.predict_proba(X_test)[:, 1]
print("Predicted Probabilities:")
print(y_pred_proba_smote)

"""**Actual vs Predicted Table**"""

actual_predicted_smote = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred_smote
})
actual_predicted_smote.head(20)

"""**Model Evaluation**"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
accuracy_smote = accuracy_score(y_test, y_pred_smote)
precision_smote = precision_score(y_test, y_pred_smote, zero_division=0)
recall_smote = recall_score(y_test, y_pred_smote, zero_division=0)
f1_smote = f1_score(y_test, y_pred_smote, zero_division=0)
roc_auc_smote = roc_auc_score(y_test, y_pred_proba_smote)
print("Accuracy:", accuracy_smote)
print("Precision:", precision_smote)
print("Recall:", recall_smote)
print("F1 Score:", f1_smote)
print("ROC-AUC:", roc_auc_smote)

"""**Evaluation Table**"""

evaluation_smote = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    "CatBoost": [
        accuracy_smote,
        precision_smote,
        recall_smote,
        f1_smote,
        roc_auc_smote
    ]
})

evaluation_smote

"""**Confusion Matrix**"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm_smote = confusion_matrix(y_test, y_pred_smote)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_smote,
    display_labels=["Class 0", "Class 1"]
)

disp.plot()

plt.title("CatBoost")
plt.show()

"""**ROC-AUC Graph**"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Calculate ROC curve
fpr_smote, tpr_smote, thresholds_smote = roc_curve(
    y_test,
    y_pred_proba_smote
)

# Calculate ROC-AUC
roc_auc_smote = roc_auc_score(
    y_test,
    y_pred_proba_smote
)

# Plot ROC-AUC Curve
plt.figure(figsize=(8, 6))

plt.plot(
    fpr_smote,
    tpr_smote,
    linewidth=2,
    label=f"CatBoost + SMOTE (AUC = {roc_auc_smote:.3f})"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    linewidth=1.5,
    label="Random Classifier"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-AUC Curve — CatBoost + SMOTE")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

"""**Comparison**"""

comparison = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    "CatBoost": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ],
    "CatBoost + SMOTE": [
        accuracy_smote,
        precision_smote,
        recall_smote,
        f1_smote,
        roc_auc_smote
    ]
})

comparison

"""**Comparison Graph**"""

import matplotlib.pyplot as plt
import numpy as np

metrics = ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"]

catboost_scores = [
    accuracy,
    precision,
    recall,
    f1,
    roc_auc
]

smote_scores = [
    accuracy_smote,
    precision_smote,
    recall_smote,
    f1_smote,
    roc_auc_smote
]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(10, 6))

plt.bar(x - width/2, catboost_scores, width, label="CatBoost")
plt.bar(x + width/2, smote_scores, width, label="CatBoost + SMOTE")

plt.xlabel("Evaluation Metrics")
plt.ylabel("Score")
plt.title("CatBoost vs CatBoost + SMOTE")
plt.xticks(x, metrics, rotation=0)
plt.ylim(0, 1)
plt.legend()

plt.tight_layout()
plt.show()